---

- name: Create user skel files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/skel/"
  loop: "{{ control_user_skel_files }}"
  when: control_user_enable_skel | bool

- name: Create user {{ control_user_name }}
  ansible.builtin.include_tasks:
    file: create-user.yml

- name: Setup user's resource directory
  ansible.builtin.include_tasks:
    file: create-directory.yml

- name: Enable sudoers
  ansible.builtin.copy:
    content: "{{ control_user_name }} ALL=(ALL) {{ control_user_sudo_commands }}"
    dest: '/etc/sudoers.d/{{ control_user_name }}'
    mode: u=rw,g=r,o=-
  when: control_user_enable_sudoers | bool

- name: SSH setup for user
  ansible.builtin.include_tasks:
    file: ssh-config.yml

- name: Copy files
  ansible.builtin.include_tasks:
    file: copy-files.yml

- name: Copy templates
  ansible.builtin.include_tasks:
    file: copy-templates.yml

- name: Copy contents
  ansible.builtin.include_tasks:
    file: copy-contents.yml

- name: Report user data
  when: control_user_enable_user_data | bool
  ansible.builtin.include_tasks:
    file: report-user-data.yml
...
