---
# -------------------------------------------------------------------------
# To Do: Implement your workload deployment tasks here
# -------------------------------------------------------------------------

- name: Example workload, print examplevariable values
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
  - "Variable 1: {{ vm_example_variable_1 }}"
  - "Variable 2: {{ vm_example_variable_2 }}"
