---
galaxy_info:
  role_name: cnv_instances
  author: Red Hat, Alberto Gonzalez (josegonz@redhat.com)
  description: |
    Example workload to be deployed onto OpenShift 4
  license: MIT
  min_ansible_version: "2.9"
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
dependencies: []
